[YouTube]
build-mode = "apk"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
cli-source = "j-hc/revanced-cli"
excluded-patches = "always-autorepeat custom-branding disable-zoom-haptics hide-shorts-components hide-captions-button hide-endscreen-cards"
version = "auto"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"

[Music]
build-mode = "apk"
patches-source = "revanced/revanced-patches"
integrations-source = "revanced/revanced-integrations"
cli-source = "j-hc/revanced-cli"
excluded-patches = ""
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
apkmirror-arch = "arm64-v8a"
